<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tmpl</string>
		<string>iapp</string>
		<string>iapp_template</string>
	</array>
	<key>foldingEndMarker</key>
	<string>^\s*\}</string>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>name</key>
	<string>F5 iApps Template Combined</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tmsh-scripts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#template</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actions</key>
		<dict>
			<key>begin</key>
			<string>(?=\bactions)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.actions.iapp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matchest the actions definition which contains the implementation, help, presenation and macro sections.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.actions.iapp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(actions)\s+(?:"replace-all-with")?</string>
					<key>name</key>
					<string>meta.section.identifier.appp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.actions.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#actions-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>actions-body</key>
		<dict>
			<key>comment</key>
			<string>The actions body. Basically just includes the definitions and a couple of administrative settings.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#definition</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>comment</key>
			<string>Matches TCL style comments and empty TCL style 'block comment.' Quotes intentional.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.pound.iappi</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.iappi</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*((#).*$\n?)</string>
					<key>name</key>
					<string>meta.comment.standalone</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>comment</key>
			<string>Matches TCL style comments and TCL style 'block comment.' Quotes intentional.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.semi-pound.iappi</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.iappi</string>
						</dict>
					</dict>
					<key>match</key>
					<string>.+((;\s*#).*$)</string>
				</dict>
			</array>
		</dict>
		<key>definition</key>
		<dict>
			<key>begin</key>
			<string>(?=\bdefinition)</string>
			<key>comment</key>
			<string>The definitions section. Really the main portion of the template definition.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.definition.iappp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(definition)\b</string>
					<key>name</key>
					<string>meta.definition.identifier.appp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.definition.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#definition-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>definition-body</key>
		<dict>
			<key>comment</key>
			<string>The body of the definition.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html-help</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#implementation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#presentation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#role-acl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#run-as</string>
				</dict>
			</array>
		</dict>
		<key>description</key>
		<dict>
			<key>comment</key>
			<string>Matches the description tag</string>
		</dict>
		<key>html-help</key>
		<dict>
			<key>begin</key>
			<string>(?=\bhtml-help)</string>
			<key>comment</key>
			<string>The html-help definition section.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.html-help.iappp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(html-help)\b</string>
					<key>name</key>
					<string>meta.html-help.identifier.appp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.html-help.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>ignore-verification</key>
		<dict>
			<key>comment</key>
			<string>Matchest the ignore-verification tag</string>
		</dict>
		<key>implementation</key>
		<dict>
			<key>begin</key>
			<string>(?=\bimplementation)</string>
			<key>comment</key>
			<string>The implementation script definition section.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.implementation.iappp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(implementation)\b</string>
					<key>name</key>
					<string>meta.implementation.identifier.appp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.implementation.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.f5.iapp.impl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>macro</key>
		<dict>
			<key>begin</key>
			<string>(?=\bmacro)</string>
			<key>comment</key>
			<string>The macro or templatized iRules definition section.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.macro.iappp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(macro)\b</string>
					<key>name</key>
					<string>meta.macro.identifier.appp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.macro.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.f5.iapp.macro</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>partition</key>
		<dict>
			<key>comment</key>
			<string>Matchest the partition tag</string>
		</dict>
		<key>prerequisite-errors</key>
		<dict>
			<key>comment</key>
			<string>Matchest the prerequisite-errors tag</string>
		</dict>
		<key>presentation</key>
		<dict>
			<key>begin</key>
			<string>(?=\bpresentation)</string>
			<key>comment</key>
			<string>The presentation or APL definition section.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.presentation.iappp</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(presentation)\b</string>
					<key>name</key>
					<string>meta.presentation.identifier.appp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.presentation.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.f5.iapp.presentation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>requires-bigip-version-max</key>
		<dict>
			<key>comment</key>
			<string>Matchest the requires-bigip-version-max tag</string>
		</dict>
		<key>requires-bigip-version-min</key>
		<dict>
			<key>comment</key>
			<string>Matchest the requires-bigip-version-min tag</string>
		</dict>
		<key>requires-modules</key>
		<dict>
			<key>comment</key>
			<string>Matchest the requires-modules tag</string>
		</dict>
		<key>role-acl</key>
		<dict>
			<key>comment</key>
			<string>The role-acl definition.</string>
		</dict>
		<key>run-as</key>
		<dict>
			<key>comment</key>
			<string>The run-as setting.</string>
		</dict>
		<key>signing-key</key>
		<dict>
			<key>comment</key>
			<string>Matchest the signing-key tag</string>
		</dict>
		<key>template</key>
		<dict>
			<key>begin</key>
			<string>(sys\s+(?:application\s+)?template)\s+([\w\.]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.application-template.iapp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.tmsh-script.iapp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>The template definition</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.template.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#template-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>template-body</key>
		<dict>
			<key>comment</key>
			<string>The body of an iApps template.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#actions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#description</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ignore-verification</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#partition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#prerequisite-errors</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#requires-bigip-version-max</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#requires-bigip-version-min</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#requires-modules</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#signing-key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tmpl-checksum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tmpl-signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#total-signing-status</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#verification-status</string>
				</dict>
			</array>
		</dict>
		<key>tmpl-checksum</key>
		<dict>
			<key>comment</key>
			<string>Matchest the tmpl-checksum tag</string>
		</dict>
		<key>tmpl-signature</key>
		<dict>
			<key>comment</key>
			<string>Matchest the tmpl-signature tag</string>
		</dict>
		<key>tmsh-scripts</key>
		<dict>
			<key>begin</key>
			<string>\b(cli\s+script)\s+([\w\.]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.actions.iapp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.tmsh-script.iapp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>It is possible to include a TMSH Script at the beginning of an iApps template definition. Possibly multiple.</string>
			<key>end</key>
			<string>}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>(?=})</string>
					<key>name</key>
					<string>meta.tmsh-script.body.iapp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.f5.iapp.impl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>total-signing-status</key>
		<dict>
			<key>comment</key>
			<string>Matchest the total-signing-status tag</string>
		</dict>
		<key>verification-status</key>
		<dict>
			<key>comment</key>
			<string>Matchest the verification-status tag</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.f5.iapp</string>
	<key>uuid</key>
	<string>b4b50bb3-2d85-4dd2-89e8-674675070160</string>
</dict>
</plist>
