<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>iappm</string>
		<string>iapp_macro</string>
	</array>
	<key>name</key>
	<string>F5 iApp Macro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^([A-Za-z_]\w*)\s*(\{)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.iapp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.iapp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>macro.iapp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#braces</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>braces</key>
		<dict>
			<key>begin</key>
			<string>(?:^|(?&lt;=\s))\{</string>
			<key>comment</key>
			<string>matches a single brace-enclosed word</string>
			<key>end</key>
			<string>\}([^\s\]]*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.iapp</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[{}\n]</string>
					<key>name</key>
					<string>constant.character.escape.iapp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inner-braces</string>
				</dict>
			</array>
		</dict>
		<key>inner-braces</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>comment</key>
			<string>matches a nested brace in a brace-enclosed word</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro-variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-code</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[{}\n]</string>
					<key>name</key>
					<string>constant.character.escape.iappm</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inner-braces</string>
				</dict>
			</array>
		</dict>
		<key>macro-code</key>
		<dict>
			<key>begin</key>
			<string>&lt;\%\s*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.iappm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\%&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\%[^&gt;]|[^%]&gt;|[^%&gt;])*</string>
					<key>name</key>
					<string>keyword.control.iappm</string>
				</dict>
			</array>
		</dict>
		<key>macro-variable</key>
		<dict>
			<key>begin</key>
			<string>&lt;\%=\s*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.iappm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*\%&gt;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.iappm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$)((?:[a-zA-Z0-9_]|::)+(\([^\)]+\))?|\{[^\}]*\})</string>
			<key>name</key>
			<string>variable.parameter.iappm</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.f5.iapp.macro</string>
	<key>uuid</key>
	<string>9d4d0087-24ff-4519-b8cd-8a4e995e88b7</string>
</dict>
</plist>
